### ISSUE TITLE
DeprecationWarning: "--compilers" will be removed in a future version of Mocha;

### ISSUE THREAD

**Issue by castaneai** [power-assert-js/espower-typescript#42]
- mocha v4.0.1
- power-assert v1.4.4
- espower-typescript v8.1.2

I got a following warning after running mocha command.

```
> mocha --compilers ts:espower-typescript/guess



DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info

  ✓ example test

  1 passing (6ms)
```

after see https://git.io/vdcSr , I've changed `--compilers` to `--require`, but no testcase found. 😢 

```
> mocha --require espower-typescript

No test files found
npm ERR! Test failed.  See above for more details.
```

Is there a solution?

**Comment by azu** [comment]
@castaneai 

> Mocha, by default, loads only .js when given a directory (and the default directory is test).
> -- https://github.com/mochajs/mocha/wiki/compilers-deprecation

Can you try following command?

```sh
mocha --require espower-typescript "test/**/*.ts"
```

**Comment by castaneai** [comment]
@azu thank you for comment, 🙇 
I tried the command, but got SyntaxError.

```
$ ./node_modules/.bin/mocha --require espower-typescript "test/**/*.ts"
/path/to/project/test/exampleTest.ts:1
(function (exports, require, module, __filename, __dirname) { import * as assert from 'power-assert'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /path/to/project/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/path/to/project/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/path/to/project/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/path/to/project/node_modules/mocha/bin/_mocha:484:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

**Comment by azu** [comment]
Opps,  should load `espower-typescript/guess` insteadof `espower-typescript`

```
mocha --require espower-typescript/guess "test/**/*.ts"
```

**Comment by castaneai** [comment]
@azu Thank you for your quick response, It is resolved!

```
$ ./node_modules/.bin/mocha --require espower-typescript/guess "test/**/*.ts"


  ✓ example test

  1 passing (7ms)
```

**Comment by azu** [comment]
We need to update README for following mocha 4 changes.

@castaneai if possible, Can you create a pull request to update README?

- Use `--require` instead of `--compiler`
- Wrap `test/**/*.ts` with double quote
  - It will need to compatible cross platform
